// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: extended_flow.proto

package proto

import (
	pb "github.com/netsampler/goflow2/v2/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtendedFlowMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BaseFlow *pb.FlowMessage        `protobuf:"bytes,1,opt,name=base_flow,json=baseFlow,proto3" json:"base_flow,omitempty"`
	// remapped in_out bytes & packets
	InBytes       uint32 `protobuf:"varint,200,opt,name=in_bytes,json=inBytes,proto3" json:"in_bytes,omitempty"`
	InPackets     uint32 `protobuf:"varint,201,opt,name=in_packets,json=inPackets,proto3" json:"in_packets,omitempty"`
	OutBytes      uint32 `protobuf:"varint,202,opt,name=out_bytes,json=outBytes,proto3" json:"out_bytes,omitempty"`
	OutPackets    uint32 `protobuf:"varint,203,opt,name=out_packets,json=outPackets,proto3" json:"out_packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendedFlowMessage) Reset() {
	*x = ExtendedFlowMessage{}
	mi := &file_extended_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedFlowMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedFlowMessage) ProtoMessage() {}

func (x *ExtendedFlowMessage) ProtoReflect() protoreflect.Message {
	mi := &file_extended_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedFlowMessage.ProtoReflect.Descriptor instead.
func (*ExtendedFlowMessage) Descriptor() ([]byte, []int) {
	return file_extended_flow_proto_rawDescGZIP(), []int{0}
}

func (x *ExtendedFlowMessage) GetBaseFlow() *pb.FlowMessage {
	if x != nil {
		return x.BaseFlow
	}
	return nil
}

func (x *ExtendedFlowMessage) GetInBytes() uint32 {
	if x != nil {
		return x.InBytes
	}
	return 0
}

func (x *ExtendedFlowMessage) GetInPackets() uint32 {
	if x != nil {
		return x.InPackets
	}
	return 0
}

func (x *ExtendedFlowMessage) GetOutBytes() uint32 {
	if x != nil {
		return x.OutBytes
	}
	return 0
}

func (x *ExtendedFlowMessage) GetOutPackets() uint32 {
	if x != nil {
		return x.OutPackets
	}
	return 0
}

var File_extended_flow_proto protoreflect.FileDescriptor

var file_extended_flow_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x70, 0x62,
	0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x01, 0x0a, 0x13,
	0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x6c, 0x6f, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x62, 0x2e,
	0x46, 0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x62, 0x61, 0x73,
	0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0xc8, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18,
	0xc9, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0xca,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0xcb,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x79, 0x6e, 0x66, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x63, 0x2f, 0x6e, 0x65, 0x74, 0x66, 0x6c,
	0x6f, 0x77, 0x32, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_extended_flow_proto_rawDescOnce sync.Once
	file_extended_flow_proto_rawDescData []byte
)

func file_extended_flow_proto_rawDescGZIP() []byte {
	file_extended_flow_proto_rawDescOnce.Do(func() {
		file_extended_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extended_flow_proto_rawDesc), len(file_extended_flow_proto_rawDesc)))
	})
	return file_extended_flow_proto_rawDescData
}

var file_extended_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extended_flow_proto_goTypes = []any{
	(*ExtendedFlowMessage)(nil), // 0: proto.ExtendedFlowMessage
	(*pb.FlowMessage)(nil),      // 1: flowpb.FlowMessage
}
var file_extended_flow_proto_depIdxs = []int32{
	1, // 0: proto.ExtendedFlowMessage.base_flow:type_name -> flowpb.FlowMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_extended_flow_proto_init() }
func file_extended_flow_proto_init() {
	if File_extended_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extended_flow_proto_rawDesc), len(file_extended_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extended_flow_proto_goTypes,
		DependencyIndexes: file_extended_flow_proto_depIdxs,
		MessageInfos:      file_extended_flow_proto_msgTypes,
	}.Build()
	File_extended_flow_proto = out.File
	file_extended_flow_proto_goTypes = nil
	file_extended_flow_proto_depIdxs = nil
}
